name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r . ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ec2-user/app
            nohup python3 app.py &
          EOF
